from langchain_core.prompts import ChatPromptTemplate

from src.aGraph.prompts import prompt

async def query_classification(state, llm):
    # easy or non-nested complex or nested complex
    result = await llm.ainvoke(prompt.format(input=state['input'], schema=state['schema']))
    state['classification'] = result.content
    return state

async def easy_query(state, llm):
    result = await llm.ainvoke(prompt.format(input=state['input'], schema=state['schema']))
    state['output'] = result.content
    return state

async def non_nested_complex_query(state, llm):
    result = await llm.ainvoke(prompt.format(input=state['input'], schema=state['schema']))
    state['output'] = result.content
    return state

async def nested_complex_query(state, llm):
    result = await llm.ainvoke(prompt.format(input=state['input'], schema=state['schema']))
    state['output'] = result.content
    return state

async def query_validation(state):

    # script to validate the code/sql generated by the graph
    
    state['validation'] = {'isvalid' : 'True',
                           'error': None}
    return state

async def self_correction(state, llm):
    error = state['validation']['error']
    result = await llm.ainvoke(prompt.format(input=state['input'], schema=state['schema'], error=error))
    state['output'] = result.content
    return state